Add header and headline section for mobile
alonsofl/dev-portfolio pull request #1
Opened 2021-06-03 17:06 UTC by alonsofl

### Summary
Added the header with the menu and the headline section with a short description and social icons for mobile.

#### Changes
- Configured linters for the project (HTML & CSS).
- Updated README.md file.
- Added .gitignore file (to ignore node_modules folder).
- Added global styles for margin, padding, box-sizing, and font-family in main.css.
- Added color variables for the project.
- Added header with "Welcome" message and hamburger menu icon.
- Added headline section with a short description and supporting text, using the colors for the project.
- Added a background image for the section.
- Added social icons for "Twitter", "LinkedIn" and "GitHub".
- Added a down arrow icon link to navigate to the next section.

2021-06-03 17:23 UTC, Shaher-11 reviewed
## _Status:_ Invalid:x:
## Hello @alonsofl 
This Code Review Request will be marked as invalid in your Dashboard because you didn't follow the correct [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122) as required for this project.
Please make the necessary changes and submit another code review request once you are ready! :smiley:

2021-06-03 18:12 UTC, mricanho requested changes
Hi @alonsofl, 

Good job so far! 🔥🔥

It is a very good first attempt Alonso, you are following the gitflow, your commit messages are descriptive, and you are using semantic HTML super well, congrats.
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

![almost there](https://user-images.githubusercontent.com/60631456/120692381-4dc27100-c46d-11eb-9c26-01d78a11577f.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 18:12 UTC, mricanho commented on index.html
> +    <h1 class="menu-title">Welcome</h1>
- [ ] Welcome it's not a title, here works kind of a logo or a subtitle, so change it for an "a" tag or a "hx"

2021-06-03 18:12 UTC, mricanho commented on index.html
> +      <h2 class="headline-title">Hey there. I'm Alonso<br><span class="headline-description">I'm a software developer</span></h2>
- [ ] This is actually the main title, so, treat it as an "h1" tag please

2021-06-03 18:12 UTC, mricanho commented on index.html
> +      </div>
- [ ] The list of icons uses a `ul` tag to group them, and `li` per icon; each icon must have a link (`a` tag)

2021-06-03 18:12 UTC, mricanho commented on README.md
> +Project to create a portfolio website.
- [ ] [OPTIONAL] You can be a little bit more descriptive with this part of the README file

2021-06-04 16:27 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @alonsofl!

You worked hard in all the instructions I gave you before👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-04 16:28 UTC, merged